<b>A pulsar is a highly magnetized rotating neutron star or white dwarf that emits a beam of electromagnetic radiation. This radiation can be observed only when the beam of emission is pointing toward Earth (much like the way a lighthouse can be seen only when the light is pointed in the direction of an observer), and is responsible for the pulsed appearance of emission.</b>

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/PIA18848-PSRB1509-58-ChandraXRay-WiseIR-20141023.jpg/223px-PIA18848-PSRB1509-58-ChandraXRay-WiseIR-20141023.jpg'></img>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['pulsar_stars.csv']


<center><font size=4px>A look at the data</font></center>

In [2]:
data=pd.read_csv('../input/pulsar_stars.csv')
data.sample(5)


Mean of the integrated profile      ...       target_class
5181                         99.000000      ...                  0
5128                        107.093750      ...                  0
13387                       101.375000      ...                  0
13814                       119.679688      ...                  0
10530                       125.554688      ...                  0

[5 rows x 9 columns]

<center><font size=4px>Correlation of columns</font></center>

In [3]:
cols=data.columns
for col in cols:
    print('Column:' + str(col))
    print(np.corrcoef(data['target_class'],data[col]))

Column: Mean of the integrated profile
[[ 1.         -0.67318058]
 [-0.67318058  1.        ]]
Column: Standard deviation of the integrated profile
[[ 1.         -0.36370821]
 [-0.36370821  1.        ]]
Column: Excess kurtosis of the integrated profile
[[1.         0.79159138]
 [0.79159138 1.        ]]
Column: Skewness of the integrated profile
[[1.         0.70952802]
 [0.70952802 1.        ]]
Column: Mean of the DM-SNR curve
[[1.         0.40087609]
 [0.40087609 1.        ]]
Column: Standard deviation of the DM-SNR curve
[[1.         0.49153506]
 [0.49153506 1.        ]]
Column: Excess kurtosis of the DM-SNR curve
[[ 1.         -0.39081632]
 [-0.39081632  1.        ]]
Column: Skewness of the DM-SNR curve
[[ 1.        -0.2591167]
 [-0.2591167  1.       ]]
Column:target_class
[[1. 1.]
 [1. 1.]]


<center><font size=4px>Encoding the target class</font></center>

In [4]:
d=pd.get_dummies(data['target_class'])
data=pd.concat([data,d],axis=1)
data.drop('target_class',axis=1,inplace=True)
data.head()

Mean of the integrated profile ...  1
0                       140.562500 ...  0
1                       102.507812 ...  0
2                       103.015625 ...  0
3                       136.750000 ...  0
4                        88.726562 ...  0

[5 rows x 10 columns]

<center><font size=4px>Making test-set</font></center>

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data.drop([0,1],axis=1),data[[0,1]],test_size=0.2)

<center><font size=4px>Neural network construction</font></center>

In [6]:
!pip install keras-metrics

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import adam
import keras_metrics as km
model=Sequential()
for i in range(0,4):
    model.add(Dense(100,input_shape=(8,),activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64,input_shape=(8,),activation='relu'))
model.add(Dense(64,input_shape=(8,),activation='relu'))
model.add(Dense(64,input_shape=(8,),activation='relu'))
model.add(Dense(64,input_shape=(8,),activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(32,input_shape=(8,),activation='relu'))
model.add(Dense(32,input_shape=(8,),activation='relu'))
model.add(Dense(32,input_shape=(8,),activation='relu'))
model.add(Dense(32,input_shape=(8,),activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2,activation='softmax'))
print('Model summary: ')
model.summary()
print('')
opt = adam(lr=0.001, decay=1e-6)
model.compile(
    loss='categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy',km.precision(),km.recall()])
print('Model fitting...')
model.fit(x_train,y_train, epochs=20, batch_size=32)
score=model.evaluate(x_test,y_test)
print('Accuracy(on Test-data): ' + str(score[1]))


Using TensorFlow backend.


Model summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 100)               900       
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_3 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_4 (Dense)              (None, 100)               10100     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 64)                6464      
_________________________________________________________________
dense_6 (Dense)              (None, 64)                4160 

<center><font size=4px>We have also achieved high precision & recall values. Since the data was heavily skewed, we can use F1 score = (2*P*R)/(P+R) for accurate measurement of our model's performance! <br>Suggestions & feedback always welcomed.</font></center>